# Generated by Django 3.2.8 on 2021-10-24 17:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('first_service_date', models.DateField()),
                ('services_per_month', models.CharField(max_length=100)),
                ('service_duration', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='')),
                ('notes', models.CharField(max_length=2000)),
            ],
        ),
    ]
