# Generated by Django 3.2.8 on 2021-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='client',
            name='service_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='services_per_month',
            field=models.IntegerField(),
        ),
    ]
