# Generated by Django 3.2.8 on 2021-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
