# Generated by Django 3.2.8 on 2021-11-17 04:00

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20211117_0338'),
        ('crew', '0005_truck_truck_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('client_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.truck')),
            ],
        ),
    ]
