# Generated by Django 3.2.8 on 2021-11-24 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0007_truck_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client_truck',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crew.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
            preserve_default=False,
        ),
    ]
