# Generated by Django 3.2.8 on 2021-11-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0008_auto_20211124_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.truck'),
        ),
    ]
