# Generated by Django 3.2.8 on 2021-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0009_auto_20211128_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
    ]
